### ISSUE TITLE
Allow user to change max variable name length and function name length

### ISSUE THREAD

**Issue by zsup** [particle-iot/device-os#101]

**Comment by m-mcgowan** [comment]
We have recently removed some redundant storage so memory use is more efficient for the variable/functions, so we can increase the maximum length. Rather than making this configurable,  would simply increasing maximum length to (say) 30 characters suffice?

**Comment by monkbroc** [comment]
All variable and function names are sent in the describe message so longer names could cause issues with the describe message being too big. The 12 character limit is a reasonable compromise.

**Comment by technobly** [comment]
Hmm even better that these are now 64 chars from #1537 😄
