### ISSUE TITLE
Photon fails to reenter listening mode following incorrect wifi credentials, still broadcasting

### ISSUE THREAD

**Issue by karlhenricksen** [particle-iot/device-os#1061]
**Description:**
This issue describes 2 different behaviors, will split into 2 if it's determined they are different:
1.  following a user sending incorrect wifi credentials (assume multiple times), Photon fails to return to blinking blue and stays blinking green indefinitely.  
2. Same as first issue EXCEPT now it is blinking green AND also broadcasting wifi AP

I believe this only occurs when a user sends wrong credentials a couple times, but it seems highly reproducible with the following steps:

**Steps to Reproduce:**
1. Reset Photon wifi credentials via setup button (hold 10+sec)
2. Reset Photon to start clean
3. Using iOS app, send incorrect wifi password to a valid SSID
4. If Photon successfully reenters wifi (blinking blue), repeat step 3 up to 10 times _without resetting the photon_

**Results**
In 9 consecutive attempts of sending wrong credentials, I saw results 4/9 failed: Pass (returned to listening mode), Pass, Fail, Pass, Fail, Pass, Fail, Pass, Fail

**Versions:**
System v0.5.2, user = tinker

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by technobly** [comment]
I was able to reproduce some stuck in green flashing behavior on 0.5.2 and 0.5.3, but when testing 0.6.1-rc.2 I have yet to see it get stuck in flashing green.  Any chance you could test this version and see if it works for you as well @karlhenricksen ?
