### ISSUE TITLE
[Enhancement] Add `operator<<` to `Print` class

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1099]
Is there a reason why there is no `operator<<` available in `Print`?
Or do I just not look in the right place to get code like 

``` cpp
Serial << "someString";
```

to work?

**Comment by technobly** [comment]
This seems like a super easy solution:
http://playground.arduino.cc/Main/StreamingOutput

One line addition, but there is a library that is included at the top of that link that provides even more support, and support for `endl`.  This might not be the full blown C++ version of the stream insertion operator, but it's a lot lighter.

```c
template<class T> inline Print &operator <<(Print &obj, T arg) { obj.print(arg); return obj; }

void setup()
{
    Serial.begin(9600);
}

void loop() { 
    char * name = "Particle";
    static const int num = 1;
    Serial << name << " is number " << num << "!\r\n";
}
```
