### ISSUE TITLE
Core can function as a HID device

### ISSUE THREAD

**Issue by AndrewKirkovski** [particle-iot/device-os#1119]
Photon & Electron have HID support, but Core has not. That kinda sucks, Core HAD working HID support in ancient branches.
See: https://github.com/spark/firmware/issues/528
See: http://community.particle.io/t/having-trouble-finding-documentation-for-emulating-a-keyboard/22983/22?u=ryotsuke

**Comment by technobly** [comment]
The Core is already very limited in flash and ram space, so adding more features will likely bankrupt the Core's usability.  There is a possibility that this could be implemented as a command line option, but is a low priority.

**Comment by Ryotsuke** [comment]
> The Core is already very limited in flash and ram space, so adding more features will likely bankrupt the Core's usability. There is a possibility that this could be implemented as a command line option, but is a low priority.

That is a weird reason. I already have a core running as HID device on older firmware version. But it needs manual changes and is not supported from Web IDE this way.

**Comment by asquelt** [comment]
can you point me to ancient firmware with HID enabled? thank you.
