### ISSUE TITLE
Serial print with HEX argument does not print leading zero

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/device-os#1121]
```
Serial.print(buffer[i], HEX);
```

when using the HEX print on serial, the leading zero is not printed for single digit values, this is really confusing, and doesn't seem to jive with hex output?

## Proposed Behavior

Serial.print(my_uint8_t, HEX); // would pad up to 2 with leading 00's
Serial.print(my_uint16_t, HEX); // would pad up to 4 with leading 0000's
Serial.print(my_uint32_t, HEX); // would pad up to 8 with leading 00000000's

## Documentation

Provide alternative examples using printf() that does the padding.

**Comment by BracWebb** [comment]
Problem is, how many leading zeros? Always enough to be two digits per length (e.g. 0x0A for 1 byte and 0x0ABC for two bytes?) .. or should the user specify length (e.g. `Serial.print(variable, HEX, 2)`)?
This should do what you need:
`Serial.print(String::format("0x%02X", variable));`
Check out `printf` formating. There is a lot you can make it do!

**Comment by dmiddlecamp** [comment]
I think if I'm printing a single character then one leading zero for HEX output makes sense?

**Comment by dmiddlecamp** [comment]
I think making the String(foo) wrapper give a nice default makes sense, and then letting users use printf for anything more fancy is the most friendly / intuitive solution?

**Comment by BracWebb** [comment]
So if you print a 16-bit variable do you want to make sure it is padded to 4 hex digits and if a 32-bit value to 8 hex digits and so on?

**Comment by technobly** [comment]
I think formatting is really a user driven thing.  If you want padding, you must specify it.  If I didn't want padding and the firmware defaults to using it, how would I disable it?

printf/printlnf is also natively supported with Serial now to make this easy.
```
Serial.printlnf("My padded hex byte is 0x%02X", hex_byte);
```

**Comment by dmiddlecamp** [comment]
Hi @BracWebb,

  That doesn't sound unreasonable, padding to the data type size makes sense, and would help align padding, etc.  There aren't a huge number of permutations here, right, just a handful?

Thanks,
David

**Comment by technobly** [comment]
I think formatting is really a user driven thing.  If you want padding, you must specify it.  If I didn't want padding and the firmware defaults to using it, how would I disable it?

printf/printlnf is also natively supported with Serial now to make this easy.
```
Serial.printlnf("My padded hex byte is 0x%02X", hex_byte);
```

**Comment by dmiddlecamp** [comment]
Hi @technobly ,

  I think my concern here is that it isn't intuitive.  I just spent a few hours trying to figure out why my output was garbled, and bytes weren't parsing as expected, only to discover a huge number of leading zeros were missing.  Maybe a good question would be: what does Arduino do for the String / HEX output?

**Comment by BracWebb** [comment]
Ha, didn't even know it was natively supported in Serial -- this convo helped me learn something! :)

**Comment by technobly** [comment]
@dmiddlecamp I think this is just a consequence of learning C/C++ and we try to stay in line with Arduino/Wiring as much as possible, but in other cases we diverge from it on purpose.  I would bet Arduino doesn't print leading zeros by default based on the data type.  I think an appropriate API would be to add a function that enables leading zeros by default if we wanted to make the firmware add them (beyond what format specifiers already do).  We have a link to format specifiers in one spot in the Docs that I know of (because I added it) http://www.cplusplus.com/reference/cstdio/printf/  but maybe we need more?

**Comment by m-mcgowan** [comment]
I would like to verify what arduino does here...and I'm hoping they pad...imho I agree with David about padding according to the datatype, since that is the element of least surprise.

**Comment by dmiddlecamp** [comment]
I don't mean to bikeshed here, this just felt inconsistent with our typical "friendly" design, and it cost me a few hours of time.  We have plenty of mechanisms to control padding the typical ways, I just think the default way should be as intuitive as possible.

Checking on Arduino it looks like they have an open issue related to this, so maybe our current Serial.print is compatible with theirs, but maybe we should both change that?

https://github.com/arduino/Arduino/issues/1097

**Comment by m-mcgowan** [comment]
As a first resolution to the issue, we can add this info to the docs so it's no longer surprising. And provide the alternative example using printf() that does the padding.

**Comment by technobly** [comment]
@dmiddlecamp I just realized your original request was for the HEX argument in Serial.print(variable, HEX); ... and that does make sense.  It's very Arduino/Wiring already by using that API.  I was only pushing back on making any changes to the way C format specifiers work by default, so don't make "%x" add any leading zeros.

Arduino has no docs saying it will add leading zeros https://www.arduino.cc/en/Serial/Print

But it's something we could diverge on :)

**Comment by dmiddlecamp** [comment]
Really great conversation overall, thanks everybody for your input and help! :) 

Yeah, I totally agree, changing behavior of something standard like printf would be really silly to do :)
