### ISSUE TITLE
[Electron] Handshake process not recovering from MBEDTLS timeout

### ISSUE THREAD

**Issue by technobly** [particle-iot/device-os#1175]
After seeing restoreStatus = 2 (NO_SESSION), a full handshake starts (send 107), but over and over times out (handshake failed -6800).  

**Possible symptom:** of root cause is cellular noise affecting the data communications bus between the STM32 and u-Blox modem.  Here's my comments from a previous encouter:

>The antenna I was using (old flexible one we used to send out with beta units) Taoglas FXP14 was spewing more radiated emissions (harmonics probably) and causing observable noise in the UART logging output (TX pin).  That was probably being seen by the electron's internal UART as well.  I was seeing more and less progression in the handshake sequence when I was moving the antenna closer and further from the electron, seemingly directly related to noise.  I switched to the PCB antenna (Taoglas PC104) and the UART noise went away completely, but the timeouts in handshake were still happening for a bit.  Then all of the sudden the entire sequence streamed through and it connected finally.

**Possible solution:** Increase the timeout max from 6000 to something larger like 30000.
    
    dtls_message_channel.cpp:216 mbedtls_ssl_conf_handshake_timeout(&conf, 3000, 6000);

```
00262387 [system] system_cloud_internal.cpp:674, Spark_Handshake(): INFO: Starting handshake: presense_announce=0
0000262508 [protocol.begin] protocol.cpp:248, particle::protocol::Protocol::begin(): INFO: Establish secure connection
0000262642 [message_channel.dtls] dtls_message_channel.cpp:349, particle::protocol::DTLSMessageChannel::establish(): INFO: setup context
0000262778 [message_channel.dtls] dtls_session_persist.h:160, particle::protocol::SessionPersist::restore_this_from(): TRACE: restore size mismatch 1: 0/220
0000262942 [message_channel.dtls] dtls_message_channel.cpp:358, particle::protocol::DTLSMessageChannel::establish(): INFO: restoreStatus = 2
0000263091 [system] system_cloud_internal.cpp:346, Spark_Send_UDP(): TRACE: send 107
socketSendTo(0,54.89.10.58,5684,,107)
   263.180 AT send      35 "AT+USOST=0,\"54.89.10.58\",5684,107\r\n"
   263.263 AT read  >    3 "\r\n@"
   263.340 AT send     107 "\x16\xfe\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x00^\x01\x00\x00R\x00\x00\x00\x00\x00\x00\x00R\xfe\xfd\x9e\x93\b\x00\xdb\xa4\xdaV\xec\xa7\x96 y\"\x01]\rp\xc87\xcc9M|S\xa0\v\xda\xf0\x15(>\x00\x00\x00\x04\xc0\xae\x00\xff\x01\x00\x00$\x00\r\x00\x06\x00\x04\x04\x03\x03\x03\x00\n\x00\x04\x00\x02\x00\x17\x00\v\x00\x02\x01\x00\x00\x13\x00\x02\x01\x02\x00\x14\x00\x02\x01\x02"
   263.854 AT read  +   17 "\r\n+USOST: 0,107\r\n"
   263.864 AT read OK    6 "\r\nOK\r\n"
0000266093 [system] system_cloud_internal.cpp:346, Spark_Send_UDP(): TRACE: send 107
socketSendTo(0,54.89.10.58,5684,,107)
   266.115 AT send      35 "AT+USOST=0,\"54.89.10.58\",5684,107\r\n"
   266.198 AT read  >    3 "\r\n@"
   266.276 AT send     107 "\x16\xfe\xfd\x00\x00\x00\x00\x00\x00\x00\x01\x00^\x01\x00\x00R\x00\x00\x00\x00\x00\x00\x00R\xfe\xfd\x9e\x93\b\x00\xdb\xa4\xdaV\xec\xa7\x96 y\"\x01]\rp\xc87\xcc9M|S\xa0\v\xda\xf0\x15(>\x00\x00\x00\x04\xc0\xae\x00\xff\x01\x00\x00$\x00\r\x00\x06\x00\x04\x04\x03\x03\x03\x00\n\x00\x04\x00\x02\x00\x17\x00\v\x00\x02\x01\x00\x00\x13\x00\x02\x01\x02\x00\x14\x00\x02\x01\x02"
   266.779 AT read  +   17 "\r\n+USOST: 0,107\r\n"
   266.789 AT read OK    6 "\r\nOK\r\n"
lib/mbedtls/library/ssl_tls.c:2334: handshake timeout
lib/mbedtls/library/ssl_tls.c:3939: mbedtls_ssl_fetch_input() returned -26624 (-0x6800)
lib/mbedtls/library/ssl_cli.c:1526: mbedtls_ssl_read_record() returned -26624 (-0x6800)
0000273023 [message_channel.dtls] dtls_message_channel.cpp:410, particle::protocol::DTLSMessageChannel::establish(): ERROR: handshake failed -6800
0000273177 [protocol.begin] protocol.cpp:256, particle::protocol::Protocol::begin(): ERROR: handshake failed with code 17
0000273305 [system] system_task.cpp:304, handle_cloud_connection(): WARN: Cloud handshake failed, code=17
0000273666 [system] system_task.cpp:464, cloud_disconnect(): INFO: Cloud: disconnecting
0000273691 [system] system_cloud_internal.cpp:1055, spark_cloud_socket_disconnect(): TRACE: Close Attempt
socketClose(0)
```

### Update 1

Saw this issue again and tried increasing the timeout value.  Increasing the timeout didn’t fix it but it does seem to increase the number of times the outgoing message can be retried (it has it’s own backoff period on that)… it’s also stuck in the `in_cloud_backoff_period()` loop… and even though the cloud connection is disconnected and reconnected… the modem is not power cycled.  The modem is sending and receiving data though so perhaps no power cycle is necessary… but sometimes possibly due to the noisy antenna the outgoing message is not received (packet corruption) because there is no response.  I switched back to the Taoglas PC104 and I’m still seeing noisy TX pin logs and still MBEDTLS timeouts.  I reset the unit and it’s still very noisy.  Something to note, I had previously forced the unit into GSM mode only (2G) mode… and that setting is persistent in NVM memory.  After forcing 3G mode, the TX pin noise is visibly gone.  The first attempt at connecting made it pretty far but still resulted in a timeout.  The second one connected.  

This issue may be caused by radiated harmonics or power supply issues in 2G mode.  
- A good recommendation would be forcing the 3G electrons to only use 3G mode which should help a lot.  There are a few simple AT commands for this.
- Part of this issue might also be cased by the higher ESR 220uF tant cap on the electron when used in 2G mode.  Test electron in 2G mode with UDP echo server and see how much noise is present with existing cap, and lower 45 mOhm tant.
- Part of this issue resolution could be choosing an antenna dedicated to the frequency used on that particular electron (i.e. U260 in 3G mode (UMTS) would only be 1900 MHz, whereas 2G mode (GSM) is 850 MHz which we could ignore in an antenna selection ).

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (v0.6.0)

**Comment by mohitbhoite** [comment]
Amazing investigation Brett. Thanks!
