### ISSUE TITLE
softap-setup equivalents over USB serial (and custom setup over other conduits)

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/device-os#1257]
In order to support complete setup of a device via USB, we need the soft AP functionality (available via TCP/HTTP) to be available via USB.

The softAP functionality is

- scanning for wifi networks (not supported over USB)
- determining and setting the active antenna (not supported over USB)
- retrieving the device ID (supported over USB)
- setting the claim code and determining if a device is claimed (already supported over USB)
- setting wifi credentials (already supported over USB in plaintext)
- retrieve the device's public key (not supported)
- naming the device (currently not supported via any interface.)
- turning on/off the device nyan LED (only supported once connected to the cloud)

Since we assume USB is a secure connection, there is no need to encrypt the wifi password with the device's public key. However, we should still provide the public key via USB in case it is required in future. 

Naming the device is a afterthought - the setup process could provide the device name, and the device name is sent to the cloud when the device is claimed. This allows the device details to be given when the device is offline, to be applied later when the device is online. 

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (as of 0.6.1)

**Comment by mebrunet** [comment]
Two thumbs up. This would be great.

As for claiming over USB, is there anything we should know to make it work right now? I'm having [issues](https://github.com/spark/firmware/issues/602#issuecomment-281183770).

**Comment by avtolstoy** [comment]
https://github.com/particle-iot/firmware-protobuf
