### ISSUE TITLE
Implement TCPServer code on Electron hardware

### ISSUE THREAD

**Issue by wvdv2002** [particle-iot/device-os#1265]
### Feature/Enhancement Request

Would it be possible to implement the functionality to use [TCPServer](https://docs.particle.io/reference/firmware/electron/#tcpserver) on an Electron?
This is not useful for the Particle Sim solution. But there are other MVNOs, like [Emnify](http://www.emnify.com), which provide a VPN network for all 3G enabled devices so these ports would be accessible in those cases.

According to the file [socket_hal.cpp](https://github.com/spark/firmware/blob/latest/hal/src/electron/socket_hal.cpp), the whole create a non blocking socket server just returns -1 at the moment of writing.

**Comment by technobly** [comment]
Thanks for the request @wvdv2002 this is possible given the right cellular networking environment as you noted.  We do accept PR's if this is something you'd like to work on.  Please update this thread if you decide to give it a go.
