### ISSUE TITLE
[USB] Provide an API to implement custom HID devices

### ISSUE THREAD

**Issue by avtolstoy** [particle-iot/device-os#1294]
## Feature/Enhancement Request

As in title. Original community forums thread: https://community.particle.io/t/is-the-photon-capable-of-running-as-a-custom-usb-hid-device-such-as-a-joystick/30397

**Comment by SreejitS** [comment]
I used Mouse.begin() to try out the HID mouse functionality on photon. It successfully enumerates and registers a IN endpoint address of 0x85. Can I know where this endpoint address are mentioned in the source code ?

I tried searching for it but couldn't find it. I would like to tweak the value so as to create a custom HID device.
