### ISSUE TITLE
WiFi.off doesn't turn off and keeps 'looking for internet' in a specific situation

### ISSUE THREAD

**Issue by kasperkamperman** [particle-iot/device-os#1303]
### Expected Behavior

WiFi.off should turn off the WiFi module and the status led should be breathing white. 

### Observed Behavior

On WiFi.off the status led blinks short white and then starts blinking green rapidly (looking for internet as written in device modes). It keeps doing that. 

Video: https://www.youtube.com/watch?v=IF2Q6xPemcI

### Steps to Reproduce

I've used the Particle app to connect to the Photon (Firmware 0.6.1). I selected my own network, but I've entered a wrong password. 

I've reset the Photon. It starts in WiFi.listening mode (code below) and after 20 seconds it tries to turn off the WiFi module. Then the green blinking starts after the white flash. 

I use SYSTEM_MODE manual, because I need to control the WiFi setup procedure myself. 

### Test App

```c
#include "Particle.h"

/*
This happens in the following situation:

WiFi network is configurated with a wrong password (with the Particle app). I couldn't
reproduce it with the setCredentials function (and a wrong password). When I go from WiFi.listen mode to WiFi.off. It shortly gives a white flash and then it starts and keeps blinking green rapidly (looking for internet).I expect that it starts breathing white directly.

Firmware version 0.6.1.
*/

SYSTEM_THREAD(ENABLED);
SYSTEM_MODE(MANUAL);

boolean wifiOff = false;

void setup()
{
  Serial.begin(57600);

  //This didn't reproduce the problem
  //WiFi.setCredentials("MyWIFINetwork", "wrongpassword");

  //To create same start situation. Clear all credentials. Use Particle app to connect to your
  //WiFi network with a wrong password. 
  //WiFi.clearCredentials();

  delay(2000);
  Serial.println("Hi! Setup!");
  pinMode(7, OUTPUT);
}

void loop()
{
  if(millis() > 20000) {
    if(wifiOff == false) {
      Serial.println("Turn WiFi off...");
      WiFi.off();
      wifiOff = true;
      digitalWrite(7, LOW);
    }
  }
  else {
    if(!WiFi.listening())	{
      Serial.println("Start listen");
      WiFi.listen();
      digitalWrite(7, HIGH);
    }
  }
}
```

**Comment by avtolstoy** [comment]
This should be resolved in recent
