### ISSUE TITLE
GCC 5.4.1 SRAM overflow on PLATFORM=electron

### ISSUE THREAD

**Issue by technobly** [particle-iot/device-os#1363]
### Expected Behavior

- v0.6.2 firmware
- compiling with GCC v5.4.1
- `cd firmware/modules`
- `make clean all -s PLATFORM=electron`
- should compile Tinker app successfully

### Observed Behavior

`error: region 'SRAM' overflowed by 20 bytes`

**Comment by sergeuz** [comment]
Some details: https://github.com/spark/firmware/pull/1159#issuecomment-262969953

**Comment by technobly** [comment]
I knew there was some info somewhere, thanks @sergeuz

**Comment by elcojacobs** [comment]
This also happens on platform P1, see:
https://community.particle.io/t/linker-error-when-trying-to-build-p1-system-modules-on-0-7-0-solved/35439

**Comment by Plasmarobo** [comment]
I've observed this issue attempting to build 0.6.4 with gcc 5.3.1 (5_3-2016q1).
In my case the SRAM is overflowed by 3052 (3060 total bytes of SRAM being consumed).
