### ISSUE TITLE
BLE APIs are not thread safe

### ISSUE THREAD

**Issue by filipnavara** [particle-iot/device-os#1519]
_NOTE: This is migrated issue from RedBear Duo firmware repository. Since there is now pull request #1505 that integrates the platform into the main repository it makes sense to move the issue here. In any case I don't think the issue should block the pull request though!_

The BTstack APIs used to implement the BLE wiring/HAL API in PR #1505 are supposed to be [single-threaded](https://bluekitchen-gmbh.com/btstack/integration/). The HAL code, however, spawns a thread that handles the BTstack execution loop. This can be done, but only when certain rules are followed, which is not the case.

Currently the APIs such as "ble.startAdvertising()" are documented to be safe to be executed in main thread in a pattern like

```
ble.init();
// do some setup
ble.startAdvertising();
```

This, in turn, triggers the calls to `hal_btstack_init` (for `ble.init`) for BTstack to be initialized, which spawns a thread at the end. By the time `hal_btstack_startAdvertising` (for `ble.startAdvertising`) is called the thread is already running and continuing the Bluetooth initialization (often the key exchange as part of BTstack's `sm_run` function).

Since the APIs are not thread safe one of the following things can occur:
- `hal_btstack_startAdvertising` calls `gap_advertisements_enable(1)`. It sets the necessary flags and proceeds to call `hci_run`. `hci_run` immediately quits on the `if (!hci_can_send_command_packet_now()) return;` condition because the worker thread is busy sending key exchange packets. In turn, the advertisements are never enabled and there's no error reported.
- `hal_btstack_startAdvertising` calls `gap_advertisements_enable(1)`. It sets the necessary flags and proceeds to call `hci_run`. `hci_run` goes past the `if (!hci_can_send_command_packet_now()) return;` check. Now depending on the thread interleaving one of these things can occur:
  - The `sm_run` key exchange on the worker fails because it can't send a packet now.
  - Both the worker thread and application thread pass through the `hci_can_send_command_packet_now` checks and end up messing up the command buffers and sending gibberish to the HCI USART communication port.

In some cases, the thread interleaving happens to be lucky and everything succeeds in the right order.

There are some ways to solve the problem, but each of them has its own drawbacks. These are the ones that I have come up with:
- Do not spawn the BLE worker thread and introduce a `ble.waitForEvents()` API that will be run in the application thread.
  - **Pros:** Easy to implement. Easy to reason about thread safety, since BTstack would be run in a single thread as intended.
  - **Cons:** Breaking API change. Harder to manage for more complex applications, especially when power management gets involved. The BLE provisioning code would need to be changed.
- Make the BLE worker thread spawning explicit by introducing a `ble.startWorker()` API. Allow all BLE API calls to be made on the application thread until the `startWorker` API is called. After that the APIs could only be called in the BLE timers and callbacks, with the exception of `ble.deInit()` (or possibly `ble.stopWorker()`). It can be combined with the `ble.waitForEvents()` API above to offer an alternative and introduce more flexibility for the application writers.
  - **Pros:** Easy to implement. Very deterministic and in line with how BTstack's official examples are written.
  - **Cons:** Breaking API change. Requires more understanding by the application developers (possibly a good thing).
- Create an event queue on the worker thread and process the APIs on the queue along with the BTstack main look.
  - **Pros:** The APIs remain the same. It doesn't block any application code by delays.
  - **Cons:** Harder to implement since almost every BLE HAL API would have to be rewritten to be queued (possibly something could be achieved by C macros). Introduces memory management for the queue, which has to handle more states.
- Implement a synchronization mechanism between the worker thread and the application thread in a way that the pauses the worker thread when an API is being executed and resumes it after. This could be achieved by a mutex that is held on the worker thread and released/reentered at a specified point. The APIs would have to enter the mutex, call the BTstack API and release the mutex, thus allowing the worker thread to proceed.
  - **Pros:** Easy to implement. No additional memory management.
  - **Cons:** Feels like a hack. May block the application thread when the BTstack thread is busy processing packets.

Note that this is very much not a theoretical problem. It keeps happening on my initialization sequence in various different ways. I spend days analyzing what is going wrong and I will happily provide more information and relevant logs. The race conditions often manifest as "invalid packet type" or "packet timeout" errors in the HCI code in hci_transport_h4_wiced.c.

**Comment by XuGuohui** [comment]
👍
