### ISSUE TITLE
Writing to serial before calling begin will crash the electron

### ISSUE THREAD

**Issue by dmiddlecamp** [particle-iot/device-os#1520]
## Bug Report

Writing to a serial port before 'begin' was called causes the device to become unresponsive.  Tested on 070.

### Expected Behavior

Expecting to see auto-initialization of serial ports and / or the system isn't crashing.

### Observed Behavior

User firmware stops running, and device becomes unresponsive to OTA after some number of characters written to the serial port.

### Steps to Reproduce

See code here: https://gist.github.com/dmiddlecamp/fbfd00420a2b5e536d839c7c01aee88a

Flash to an electron

**Comment by technobly** [comment]
Just tried this on 1.4.3 Electron LTE and it doesn't crash, but it does get stuck/blocked.  D7 stops blinking in your example app.  I agree this should likely have a safety check, if Serial/Serial1/etc. is not .begin()/initialized... it should just return (or return with error code if appropriate).

Should also be documented as such.

Until then, then obvious workaround is to not do that :D always initialize your Serial objects before using them.
