### ISSUE TITLE
0.6.3 to 0.7.0 goes wrong with at least 5 out of 5 devices I own

### ISSUE THREAD

**Issue by kasperkamperman** [particle-iot/device-os#1526]
## Bug Report
I hope this issue can be fixed. I'm getting a bit disappointed in the support of Particle. First it took really long before 0.7.0 was released and now it fails on all my devices. In the communication you state that the Photon will be still supported. I hope you do and that not al the resources go now to the 3rd generation of devices. 

I gave detailed debug steps in this forum post. After that it stays quiet. I hope that submitting this issue will help to get this problem under the attention again:
https://community.particle.io/t/update-to-0-7-0-goes-wrong/

### Expected Behaviour

Connect to the Particle cloud. 

### Observed Behavior

Don't connect to the Particle cloud. 

### Steps to Reproduce

Online
- I start with the Photon connected to the cloud and running 0.6.3 firmware. 
- To be sure I've also flashed the Tinker application to it (targeted at 0.6.3).
- On my Android phone I've tested the Tinker app by turning pin D7 High/Low. 
- I go to build.particle.io. 
- I select the tinker firmware and I star the device (Tinker is targeted at 0.7.0). 
- I flash tinker to the device (with build.particle.io). 
- It seems to update the firmware, reconnects to the cloud, but in the last step it fails to connect. I think it's the bootloader step, since the D7 LED starts softly glowing at that moment. 
- In the end I end up with a fast blinking green status led. 

Event Log
```
spark/flash/statussuccess April 14th at 6:46:40 pm
{"data":"success ","ttl":60,"published_at":"2018-04-14T16:46:40.277Z","coreid":"370038000547353138383138","name":"spark/flash/status"}
spark/flash/statusstarted April 14th at 6:46:33 pm
{"data":"started ","ttl":60,"published_at":"2018-04-14T16:46:33.275Z","coreid":"370038000547353138383138","name":"spark/flash/status"}
spark/status/safe-mode{"f":[],"v":{},"p":6,"m":[{"s":16384,"l":"m","vc":30,"vv":30,"f":"b","n":"0","v":11,"d":[]},{"s":262144,"l":"m","vc":30,"vv":30,"f":"s","n":"1","v":205,"d":[]},{"s":262144,"l":"m","vc":30,"vv":30,"f":"s","n":"2","v":109,"d":[{"f":"s","n":"1","v":109,"_":""}]},{"s":131072,"l":"m","vc":30,"vv":26,"u":"F31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8","f":"u","n":"1","v":5,"d":[{"f":"s","n":"2","v":207,"_":""}]},{"s":131072,"l":"f","vc":30,"vv":0,"d":[]}]}April 14th at 6:46:31 pm
{"data":"{\"f\":[],\"v\":{},\"p\":6,\"m\":[{\"s\":16384,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"b\",\"n\":\"0\",\"v\":11,\"d\":[]},{\"s\":262144,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"s\",\"n\":\"1\",\"v\":205,\"d\":[]},{\"s\":262144,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"s\",\"n\":\"2\",\"v\":109,\"d\":[{\"f\":\"s\",\"n\":\"1\",\"v\":109,\"_\":\"\"}]},{\"s\":131072,\"l\":\"m\",\"vc\":30,\"vv\":26,\"u\":\"F31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8\",\"f\":\"u\",\"n\":\"1\",\"v\":5,\"d\":[{\"f\":\"s\",\"n\":\"2\",\"v\":207,\"_\":\"\"}]},{\"s\":131072,\"l\":\"f\",\"vc\":30,\"vv\":0,\"d\":[]}]}","ttl":60,"published_at":"2018-04-14T16:46:31.001Z","coreid":"370038000547353138383138","name":"spark/status/safe-mode"}
spark/device/last_resetuserApril 14th at 6:46:29 pm
{"data":"user","ttl":60,"published_at":"2018-04-14T16:46:29.760Z","coreid":"370038000547353138383138","name":"spark/device/last_reset"}
device came onlineno dataApril 14th at 6:46:29 pm
{"data":"online","ttl":60,"published_at":"2018-04-14T16:46:29.557Z","coreid":"370038000547353138383138","name":"spark/status"}
spark/flash/statussuccess April 14th at 6:46:12 pm
{"data":"success ","ttl":60,"published_at":"2018-04-14T16:46:12.258Z","coreid":"370038000547353138383138","name":"spark/flash/status"}
spark/flash/statusstarted April 14th at 6:46:12 pm
{"data":"started ","ttl":60,"published_at":"2018-04-14T16:46:12.066Z","coreid":"370038000547353138383138","name":"spark/flash/status"}
spark/device/app-hashF31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8April 14th at 6:46:09 pm
{"data":"F31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8","ttl":60,"published_at":"2018-04-14T16:46:09.786Z","coreid":"370038000547353138383138","name":"spark/device/app-hash"}
spark/status/safe-mode{"f":[],"v":{},"p":6,"m":[{"s":16384,"l":"m","vc":30,"vv":30,"f":"b","n":"0","v":11,"d":[]},{"s":262144,"l":"m","vc":30,"vv":30,"f":"s","n":"1","v":109,"d":[]},{"s":262144,"l":"m","vc":30,"vv":30,"f":"s","n":"2","v":109,"d":[{"f":"s","n":"1","v":109,"_":""}]},{"s":131072,"l":"m","vc":30,"vv":26,"u":"F31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8","f":"u","n":"1","v":5,"d":[{"f":"s","n":"2","v":207,"_":""}]},{"s":131072,"l":"f","vc":30,"vv":30,"u":"0A086F060A080000000000000000B1060A08D5060A08E1060A084D0B0A08BD06","f":"u","n":"1","v":3,"d":[{"f":"s","n":"2","v":9,"_":""}]}]}April 14th at 6:46:09 pm
{"data":"{\"f\":[],\"v\":{},\"p\":6,\"m\":[{\"s\":16384,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"b\",\"n\":\"0\",\"v\":11,\"d\":[]},{\"s\":262144,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"s\",\"n\":\"1\",\"v\":109,\"d\":[]},{\"s\":262144,\"l\":\"m\",\"vc\":30,\"vv\":30,\"f\":\"s\",\"n\":\"2\",\"v\":109,\"d\":[{\"f\":\"s\",\"n\":\"1\",\"v\":109,\"_\":\"\"}]},{\"s\":131072,\"l\":\"m\",\"vc\":30,\"vv\":26,\"u\":\"F31AB658B5D1065FDD8C7798D21E22EC83C6AA5EB3B0C7776ABF569D63B481C8\",\"f\":\"u\",\"n\":\"1\",\"v\":5,\"d\":[{\"f\":\"s\",\"n\":\"2\",\"v\":207,\"_\":\"\"}]},{\"s\":131072,\"l\":\"f\",\"vc\":30,\"vv\":30,\"u\":\"0A086F060A080000000000000000B1060A08D5060A08E1060A084D0B0A08BD06\",\"f\":\"u\",\"n\":\"1\",\"v\":3,\"d\":[{\"f\":\"s\",\"n\":\"2\",\"v\":9,\"_\":\"\"}]}]}","ttl":60,"published_at":"2018-04-14T16:46:09.785Z","coreid":"370038000547353138383138","name":"spark/status/safe-mode"}
spark/device/last_resetuserApril 14th at 6:46:08 pm
{"data":"user","ttl":60,"published_at":"2018-04-14T16:46:08.540Z","coreid":"370038000547353138383138","name":"spark/device/last_reset"}
device came onlineno dataApril 14th at 6:46:08 pm
{"data":"online","ttl":60,"published_at":"2018-04-14T16:46:08.334Z","coreid":"370038000547353138383138","name":"spark/status"}
spark/flash/statussuccess April 14th at 6:46:04 pm
{"data":"success ","ttl":60,"published_at":"2018-04-14T16:46:04.675Z","coreid":"370038000547353138383138","name":"spark/flash/status"}
spark/flash/statusstarted April 14th at 6:46:04 pm
```

I can revert to a cloud connection by flashing 0.6.3 in DFU mode:
` particle flash --usb system-part1-0.6.3-photon.bin`
` particle flash --usb system-part2-0.6.3-photon.bin`

However then I get into an endless loop since again it will start the 0.7.0 firmware update. 

In my own user firmware I use this like WiFi.manual() and system thread mode. However I suppose by flashing Tinker all my user code is overwritten. 

### Test App

Tinker

### References

Links to the Community, Docs, Other Issues, etc..

**Comment by kasperkamperman** [comment]
Hi ScruffR,
I think I described and did what you suggest. But I made it more clear, what I said a start from 0.6.3 Tinker (changed my description above to make that more clear). 

I'll try downgrading in a different order, however that's not the main problem. The main problem is that update to 0.7.0 fails. I don't prefer to downgrade at all.

**Comment by ScruffR** [comment]
PMed for further investigation of possible cause.

**Comment by kasperkamperman** [comment]
Trials as communicated with ScruffR. I hope some progress will be shared by Particle, because until now it stays pretty silent. In way like it works in our testing networks, so the problem is kind of non-existant. 

## Mobile hotspot tryout 

Ok, I could get a device to update with my mobile hotspot. 

Indeed I got the 5 safe-mode-updater events. I'll need to check at home in which step I get stuck. 

```
event: spark/safe-mode-updater/updating
data: {"data":"1","ttl":60,"published_at":"2018-04-16T12:27:27.761Z","coreid":"particle-internal"}

event: spark/safe-mode-updater/updating
data: {"data":"2","ttl":60,"published_at":"2018-04-16T12:28:03.768Z","coreid":"particle-internal"}

event: spark/safe-mode-updater/updating
data: {"data":"0","ttl":60,"published_at":"2018-04-16T12:28:44.590Z","coreid":"particle-internal"}

event: spark/safe-mode-updater/updating
data: {"data":"1","ttl":60,"published_at":"2018-04-16T12:29:20.400Z","coreid":"particle-internal"}

event: spark/safe-mode-updater/updating
data: {"data":"2","ttl":60,"published_at":"2018-04-16T12:29:54.196Z","coreid":"particle-internal"}
```

Ok, I found some time to test it again on my home network. It does only the first two steps, then it hangs...
```
event: spark/safe-mode-updater/updating
data: {"data":"1","ttl":60,"published_at":"2018-04-18T21:44:48.004Z","coreid":"particle-internal"}

event: spark/safe-mode-updater/updating
data: {"data":"2","ttl":60,"published_at":"2018-04-18T21:45:24.352Z","coreid":"particle-internal"}
```
If I then power on my mobile phone hotspot, it continues. 

It's interesting to see what's going on. I can imagine more Particle devices being used in home networks. My network is stable and I'm happily surfing on the net with multiple devices on high speed. 

Your DHCP theory might work, however if I revert to 0.6.3 it directly connects to the cloud. 

How can I help to test? Might it be worth it to set a static Ip in the device (https://docs.particle.io/reference/firmware/photon/#setstaticip-). I did this with my WiFi credentials now as well, I think it's stored in the EEPROM so even with firmware updates the IP should stay static I think?

Would that be a good test to see if it's something related to the DHCP?

## Try-out by setting a static ip like below messed up my Photon (can't get it online even not when going back to 0.6.3)


I've build the following code to set my device to a static ip based on the ip information from the DHCP:
https://go.particle.io/shared_apps/5ae83294105a0839020011fe

My idea is to see what happened with a static ip configured. 

Running the script gives me the following result:
my current IP address:  192.168.1.18
my current subnet Mask: 255.255.255.0
my current gateway IP:  192.168.1.1
my current dns IP:      0.0.0.0

After I did this, I did another reboot to see if the static ip would be used. This fails. The device won't connect to the cloud anymore. It blinks rapidly light blue, with 3 orange blinks in between. 

I tried updating the Photon locally to use dynamicIP with the code below, however that won't work either. 
- Replacing the system firmware not. 
- Particle doctor also doesn't work after setting antenna to internal I get:
```? Select the antenna to use to connect to Wi-Fi Internal
The Doctor didn't complete sucesfully. undefined
```
- I tried skipping the steps untill set IP, this gives the following error:
```
? Select how the device will be assigned an IP address Dynamic IP
The Doctor didn't complete sucesfully. "path" is not defined: undefined
> Please visit our community forums for help with this error:
```

Any other way to reset the WiFi chip to use dynamic IP?

```
#include "Particle.h"

IPAddress myAddress;
IPAddress netmask;
IPAddress gateway;
IPAddress dns;

String firmwareVersion;
String publishInformation;

void setup() {


    //while(!Serial.available())
    //Particle.process();

    WiFi.useDynamicIP();

    myAddress = WiFi.localIP();
    netmask   = WiFi.subnetMask();
    gateway   = WiFi.gatewayIP();
    dns       = WiFi.dnsServerIP();

    firmwareVersion = System.version().c_str();

    publishInformation += "my current firmware:    " + firmwareVersion + "\n";
    publishInformation  = "my current IP address:  " + String(myAddress) + "\n";
    publishInformation += "my current subnet Mask: " + String(netmask) + "\n";
    publishInformation += "my current gateway IP:  " + String(gateway) + "\n";
    publishInformation += "my current dns IP:      " + String(dns) + "\n";

    //WiFi.setStaticIP(myAddress, netmask, gateway, dns);

    // now let's use the configured IP
    //WiFi.useDynamicIP();
    //Serial.println("Static IP is set");

    Particle.publish("address info", publishInformation, 60, PRIVATE);
    Particle.variable("getInfo", publishInformation);

    Serial.begin(9600);
}

void loop() {
    digitalWrite(D7, HIGH);

    Serial.println(publishInformation);


    // Prints out the local IP over Serial.
    //Serial.println("my current IP address:  " + myAddress);
    //Serial.println("my current subnet Mask: " + netmask);
    //Serial.println("my current gateway IP:  " + gateway);
    //Serial.println("my current dns IP:      " + dns);

    delay(1000);
    digitalWrite(D7, LOW);
    delay(1000);
}

```

**Comment by kasperkamperman** [comment]
The device number I have still trouble with is 410024000447343339373536. This gives me a lightblue blink and three orange flashes. What does this mean? 

I think the static ip update before updating to new firmware script is a bad idea or not? Or is there a proper way to do it?

**Comment by m-mcgowan** [comment]
You should not need to set a static IP, and I feel that will only compound the issues in general, although if there was a specific reason why you think that might have been necessary in this case, I'd love to hear it. 

The 3 orange flashes indicates a problem where the device can connect to the cloud but not complete a successful handshake. The instructions here show you how to fix this. https://community.particle.io/t/photon-flashing-cyan-and-blinking-orange/21530/6?u=mdma. 

Before following these instructions, it's a good idea to take a copy of the DCT region for later analysis - 
```
dfu-util -d 2b04:d006 -a 0 -s 0x8004000:0x8000 -U 3_orange_flashes.bin
```

I hope that helps!

**Comment by ScruffR** [comment]
@m-mcgowan, a recent post may have revealed some link between this issue and #1556

https://community.particle.io/t/update-to-0-7-0-goes-wrong/40700/56?u=scruffr

**Comment by kasperkamperman** [comment]
I can confirm. The mode of my router is n only:

> 802.11 Mode:802.11n only

**Comment by technobly** [comment]
@kasperkamperman if you have the ability to check #1755 to see if it resolves the issue for you, your feedback would be appreciated.
