### ISSUE TITLE
0.7.0 bootloader Core issues

### ISSUE THREAD

**Issue by robertdolca** [particle-iot/device-os#1545]
### Expected Behavior

When flashing yellow (DFU mode) device available as USB TTY and accessible with dfu-util.

### Observed Behavior

After upgrading the firmware to 0.7.0 the device dfu mode does not seem to work.

### Steps to Reproduce

Flash 0.7.0 firmware
Put the device in DFU mode
Try to flash something to it

**Comment by avtolstoy** [comment]
Core EOL.
