### ISSUE TITLE
WiFi.off (without Particle.disconnect) blocks indefinitely

### ISSUE THREAD

**Issue by edelmar** [particle-iot/device-os#1549]
In single threaded operation and SEMI_AUTOMATIC mode, turning off the WiFi by calling WiFi.off() without first calling Particle.disconnect() causes loop to stop running. This problem is observed with the following code (Photon 0.7.0).

```cpp
unsigned long now;

SYSTEM_MODE(SEMI_AUTOMATIC);

void setup() {
	delay(10000); // delay to allow current measurement to be observed
	pinMode(D7, OUTPUT);
	now = millis();
}


void loop() {
	static unsigned long counter = 0;
	if (counter % 50000 == 0) {
		digitalWrite(D7, !digitalRead(D7));
	}

	if (millis() - now >= 30000) {
		now = millis();
		Particle.connect();
		if (waitFor(Particle.connected, 30000)) {
			Particle.publish("test", "abcdefghijklmnopqrstuvwxyz");
			delay(5000);
			WiFi.off();
		}else{
			delay(500);
			System.reset();
		}
	}
	counter++;
}
```
After WiFi.off() is called the LED stops blinking (and Serial print statements are not executed if included), and the device breathes white indefinitely. Measurement of the Photon's current draw confirms that the WiFi module is indeed turned off. 

https://community.particle.io/t/wifi-off-without-particle-disconnect-blocks-indefinitely/42430/2

**Comment by avtolstoy** [comment]
This should be resolved in 2.x DeviceOS releases.

Please do reopen the issue if it still persists.
