### ISSUE TITLE
TCP/IP Stack for Photon

### ISSUE THREAD

**Issue by cbaser** [particle-iot/device-os#1555]
Hello,
I have a new Photon and I would like to use TCP/IP stack such as LwIP of it.
Which library should I use it?
Thank you.

**Comment by rickkas7** [comment]
There is already support for TCP/IP within the existing Particle system firmware.

https://docs.particle.io/reference/firmware/photon/#tcpclient
https://docs.particle.io/reference/firmware/photon/#tcpserver
https://docs.particle.io/reference/firmware/photon/#udp

For questions about using these APIs, not covered in the documentation, the [Community Forums](https://community.particle.io) is a better choice than Github issues.
