### ISSUE TITLE
Incompatibility between WLanSecurityType and SecurityType

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1562]
As discussed in this thread 
https://community.particle.io/t/setsecurity-doesnt-seem-to-be-working-compiling/43226

There is an incompatiblity between `WLanSecurityType` and `SecurityType` which causes the documented syntax to fail
https://docs.particle.io/reference/firmware/photon/#setsecurity-
```
// SYNTAX
WiFiCredentials& WiFiCredentials::setSecurity(SecurityType security);
// EXAMPLE - setting security type
WiFiCredentials credentials;
credentials.setSecurity(WPA2);
```
*(tested with 0.7.0 and 0.8.0-rc.8)*

But this works
```
  WiFiCredentials credentials;
  credentials.setSecurity(WLAN_SEC_WPA2);
```

**Comment by avtolstoy** [comment]
Resolved in #2098
