### ISSUE TITLE
Reset "connected" in the cloud on deliberate disconnect

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1564]
Since it keeps coming up in the forum that offline devices are marked as connected, it might be worth considering whether a deliberate disconnect (e.g. `Particle.disconnect()`, `System.sleep()`, ...) just sends a brief "goodbye" message to the cloud to reset the flag - particularly on Electrons.

**Comment by avtolstoy** [comment]
Resolved in https://github.com/particle-iot/device-os/pull/1899
