### ISSUE TITLE
device RSA public and private key changed unexpected

### ISSUE THREAD

**Issue by aeris-ming** [particle-iot/device-os#1571]
System-Firmware version:0.6.4-Photon

1.call WiFi.clearCredentials(); call SoftAP api 192.168.0.1/configure-ap set WiFi ssid and psw then Photon connected to server successfully
2.after connect to server successfully 18 times,device can not connect to server because of key issue
3.read out the private key from Photon and compare to the backup file,They are not the same

I need to know when the device key will be replace by system thread?
Thanks!

**Comment by avtolstoy** [comment]
DCT corruption on Gen 2 devices should be resolved in recent releases.
