### ISSUE TITLE
Arduino library compatibility needs #define SPI_HAS_TRANSACTION 1

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1668]
Many recent Arduino libraries rely on the existence of `#define SPI_HAS_TRANSACTION 1` when the platform supports SPI transactions.
Since Particle devices do, we should also have that macro defined (in `Particle.h` not only `Arduino.h`)

See this discussion
https://community.particle.io/t/electron-ssd1351-oled-sdcard-issues-with-adafruit-ssd1351-sdfat-libs/46798/2?u=scruffr

e.g. these libraries
https://github.com/technologiescollege/arduino/blob/master/hardware/arduino/avr/libraries/SPI/src/SPI.h
https://github.com/adafruit/Adafruit-GFX-Library/blob/master/Adafruit_SPITFT_Macros.h
https://github.com/adafruit/Adafruit_VS1053_Library/blob/master/Adafruit_VS1053.cpp
https://github.com/adafruit/Adafruit_SSD1305_Library/blob/master/Adafruit_SSD1305.cpp
https://github.com/esp8266/Basic/blob/master/libraries/Adafruit_STMPE610/Adafruit_STMPE610.cpp

**Comment by ScruffR** [comment]
This also touches on a realated issue
https://github.com/particle-iot/cloud/issues/57

**Comment by ScruffR** [comment]
Still no comment?
Another member got bitten by that https://community.particle.io/t/ssd1305-issues-on-spi/50958

**Comment by psherk-cryo** [comment]
Yep, the lack of this definition cost us a lot of time, specifically related to SDFat and an SSD1305 OLED driver.  We built our own library for the OLED, but it looks like SDFat uses the SPI_HAS_TRANSACTION define, which caused a lot of very random and hard to debug issues.  Please fix this one Particle.

**Comment by karlg100** [comment]
I'll bump this issue.  many Adafruit libraries seem to be nonfunctional from this.

**Comment by pkourany** [comment]
Bumping again.
