### ISSUE TITLE
Does EEPROM.put support power-fail recovery?

### ISSUE THREAD

**Issue by aeris-ming** [particle-iot/device-os#1676]
According to document EEPROM.put should support power-fail recovery.

```
https://docs.particle.io/reference/device-os/firmware/photon/#put-

If the Photon loses power before the write finishes, the partially written data will be ignored.
```

According to source code EEPROM.put do not support power-fail recovery.

`https://github.com/particle-iot/device-os/blob/v0.5.4/services/inc/eeprom_emulation.h`

Which one is wrong?Reference document or Source code?

**Comment by monkbroc** [comment]
The EEPROM.put supports power-fail recovery. See https://github.com/particle-iot/device-os/blob/v0.5.4/services/inc/eeprom_emulation.h#L207
