### ISSUE TITLE
[Gen3] USARTSerial::read() returns -260 instead of -1 for empty RX buffer

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1737]
Unlinke the [documentation](https://docs.particle.io/reference/device-os/firmware/xenon/#read-) states 
![image](https://user-images.githubusercontent.com/6604878/55158025-333e3000-515e-11e9-9ee3-0a762312d2f8.png)

and also in contradiction to the known behaviour of Gen1 & Gen2 devices Gen3 returns -260 instead of -1

Tested with 0.9.0

**Comment by ScruffR** [comment]
This should be dealt with in parallel with an issue discussed with @avtolstoy  and @rickkas7  3/12/2019 about potential miscalculation of `USARTSerial::available()`.

There also is a report where code like
```
  while(Serial1.available()) Serial1.read(); 
```
seems to be blocking forever which shouldn't be the case even with permanently sending 115200 clients.

**Comment by avtolstoy** [comment]
Isn't it 'blocking' simply because it instead should be `while (Serial1.available() > 0)` ?

**Comment by ScruffR** [comment]
Since `Serial1.available()` should only ever render zero or positive values but *never* negative your version should be equal to `Serial1.available() != 0` which in turn again is the same as `Serial1.available() != false` which in turn again would be equal to `Serial1.available()` - at least that would be my take on the matter.

**Comment by nzottmann** [comment]
I think there are deeper problems than described here, there are cases where `Serial1.available()` and `Serial1.read()` return wrong numbers. This can be positive numbers even if no data is available or wrong positive numbers if data is available.
See [this thread](https://community.particle.io/t/is-the-mesh-devices-uart-implementation-buggy/48854/34) in the Particle forum for example code for reproducing these issues.
