### ISSUE TITLE
1.2.1-rc.2 regression: Only three of four Particle.subscribe handlers get registered

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#1811]
With this simple test code only the handlers t1..t3 get called t4 doesn't do anything.
```
void setup() {
  Serial.begin();
  Particle.subscribe("t1", test, MY_DEVICES);
  Particle.subscribe("t2", test, MY_DEVICES);
  Particle.subscribe("t3", test, MY_DEVICES);
  Particle.subscribe("t4", test, MY_DEVICES);
}

void test(const char* event, const char* data) {
  Serial.println(event);
}
```
This works as expected (t1..t4) with 1.1.0 but 1.2.1-rc.2 fails (not tried intermediate RCs)
Tested with Photon and Argon.

**Comment by m-mcgowan** [comment]
This makes sense. There are 5 slots for subscription handers, and we added an additional system subscription for `particle/` system events (`spark/` was already registered.)   The fix will be to increase the number of handlers to 6 to avoid the regression.
