### ISSUE TITLE
TCPClient connect() will return true is given an unresolvable hostname

### ISSUE THREAD

**Issue by jchernus** [particle-iot/device-os#1865]
### Expected Behavior

TCPClient.connect() should return false if it is unable to establish a connection with the specified ip/hostname and port.

### Observed Behavior
 
If a bogus hostname is provided (not a URL at all, but jibberish), the connect() call returns true. It executes much quicker than if real URL was provided.

### Steps to Reproduce

Ran this on an electron, OS 1.2.1. Call TCPClient connect() providing a hostname that will not resolve (enter jibberish, such as 'sdfjsdlkjfs'). Connect() will return true.

### Test App

Add a basic test function, like the one below, and specify a port that you know is open on a URL of your choosing.

```c
int LoraListener::testFunction(String value) {
	char mURL[128];
	strcpy(mURL, value.c_str());
	uint16_t mPort = 3000;

	Log.info("Connecting to %s on port %i", mURL, mPort);

	TCPClient mClient;
	return mClient.connect(mURL, mPort);
}
```

Calling the function, and passing jibberish, will return a 1.

### References

https://docs.particle.io/reference/device-os/firmware/electron/#connect--1

---

**Comment by avtolstoy** [comment]
@jchernus Thanks for submitted the issue. I've confirmed that we have mixed up return values in `connect()` and sometimes return non-zero error codes to indicate an error, while also returning positive values to indicate success (true).
