### ISSUE TITLE
[Gen 3] retained int value is not initialized

### ISSUE THREAD

**Issue by shanevanj** [particle-iot/device-os#1919]
<details>
  <summary><i>retained int returns wrong value on first use and after system reset</i></summary>

</details>

### Expected Behavior

Serial output:
Starting retained var test
savedValue=0
savedValue=1
savedValue=2
savedValue=3
savedValue=4

etc...

### Observed Behavior

Serial output:
Starting retained var test
savedValue=-778261199
savedValue=-778261198
savedValue=-778261197
savedValue=-778261196
savedValue=-778261195
savedValue=-778261194
savedValue=-778261193
savedValue=-778261192
savedValue=-778261191

### Steps to Reproduce

Firmware 1.4.0 (also confirmed on 1.4.2)
flash Test app
Device is a standalone argon with no battery

### Test App

```

STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY)); 
retained int savedValue = 0; 

void setup() {
    Serial.begin(115200);
    
    while (!Serial.isConnected())
    Particle.process();
    Serial.printf(
      "\nStarting retained var test");
} 

void loop() { 
    Serial.printlnf("savedValue=%d", savedValue++); 
    delay(1000);
}

```

### References

https://community.particle.io/t/retained-memory-tips/38137
https://community.particle.io/t/retained-memory-not-working-correctly/46869
https://community.particle.io/t/retained-memory-support-on-gen-3-devices/50512/5

---

## Feature/Enhancement Request

retain an int value for use between soft restarts

**Comment by shanevanj** [comment]
Community thread

> https://community.particle.io/t/retained-memory-tips/38137

**Comment by technobly** [comment]
Thanks @shanevanj for the report.  I have confirmed this is not initializing as it should on Argon and with the latest firmware 1.4.2.  We will look into it.
