### ISSUE TITLE
BLE Allocate memory failed after running for long time

### ISSUE THREAD

**Issue by sviraaj** [particle-iot/device-os#1926]
<details>
  <summary><i>submission notes</i></summary>
</details>

## Bug Report
Setup: Xenon central with Multiple peripherals. Since currently device OS supports max 3 peripherals to be connected to Xenon central, can test with 3. More the number of peripherals earlier the repro.

Seeing the following error after running for long times. If number of peripherals) (i.e. number of central links) increased to 8, repro will can be seen within 20-30 mins. 
For a quick test with 8 peripherals use the following commit for supporting 8 peripherals:
https://github.com/sviraaj/device-os/commit/00304d54f4be3870daad0023b1a138ec32fa1683

```
ERROR: Allocate memory for received data failed.
ERROR: Allocate memory for BLE event failed.
ERROR: Allocate memory for adv report data failed.
ERROR: Allocate memory for adv report data failed.
```

### Expected Behavior

Should work without error

### Observed Behavior
Observing the above ERROR prints

### Steps to Reproduce
Run any Xenon central example with multiple peripherals (having data notify property for any characteristics) and keep running for some time. With 8 peripherals connected, error should repro in less than 30 mins (hopefully).

### References

https://github.com/sviraaj/device-os/commit/00304d54f4be3870daad0023b1a138ec32fa1683

---

**Comment by XuGuohui** [comment]
@sviraaj Could you tell me more parameters about the BLE connectivity, like how often those peripherals sending notification? Besides, according to the log, the central kept scanning BLE peripherals, right?

**Comment by sviraaj** [comment]
@XuGuohui The peripherals send a notification every 30 seconds. The scanning does continue, but fails to retrieve any allocate memory for advertising data.

**Comment by XuGuohui** [comment]
This is either encountered by the limited preallocated RAM for the BLE event pool or memory leak of the pool. Since the central are connecting to 8 peripherals sending notification and keep scanning, the pool preallocated is not large enough for caching incoming BLE events. Would you mind help running you project again after increasing the size of the preallocated pool: https://github.com/particle-iot/device-os/blob/develop/hal/src/nRF52840/ble_hal.cpp#L85? In the other hand, I'll try to figure out whether there is memory leak regarding the BLE event pool.

**Comment by sviraaj** [comment]
@XuGuohui Sure. I will check it with the above change. Just FYI, I was able to see an error even in case of 3 peripherals, after running for a longer time. Thanks.

**Comment by XuGuohui** [comment]
I just figured out a memory leak, which is triggered by the situation that when there is BLE scan result event not being processed while the BLE scanning procedure has been terminated:https://github.com/particle-iot/device-os/blob/develop/hal/src/nRF52840/ble_hal.cpp#L1459, or something went wrong on a scan result event:https://github.com/particle-iot/device-os/blob/develop/hal/src/nRF52840/ble_hal.cpp#L1488.

**Comment by XuGuohui** [comment]
So after applying the patch under [PR1929](https://github.com/particle-iot/device-os/pull/1929), devices have been running for 1.5 hour without any memory allocation failure.

**Comment by sviraaj** [comment]
@XuGuohui Great! I will run it with this patch. Thanks.
