### ISSUE TITLE
Release 1.4.3 is missing P1 system part 2

### ISSUE THREAD

**Issue by elcojacobs** [particle-iot/device-os#1981]
System part 2 binary is missing in release 1.4.3 for platform P1. Our CI is failing because of this.

**Comment by elcojacobs** [comment]
From the asset count, looks like you are missing 2 files.

**Comment by avtolstoy** [comment]
Thanks for reporting the issue. The other one was Xenon system-part1. For some reason those two binaries were in an error state and GitHub was asking to reupload them. Should be fixed now.
