### ISSUE TITLE
Firmware flash: Unused buffer may indicate usage of wrong variable

### ISSUE THREAD

**Issue by perotom** [particle-iot/device-os#1989]
After I got some problems writing my OTA update over HTTP to the flash I discovered that after a write to the flash of "Not an aligned data" (https://github.com/particle-iot/device-os/blob/a7aabdfce6a0f036e6493544ff9246f81d2a51c3/platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c#L901) subsequent writes will fail. I looked at the corresponding code and found that the array `buf` (https://github.com/particle-iot/device-os/blob/a7aabdfce6a0f036e6493544ff9246f81d2a51c3/platform/MCU/STM32F2xx/SPARK_Firmware_Driver/src/flash_mal.c#L903) is filled but never used. Could it be possible that there is something wrong with this code block?

**Comment by avtolstoy** [comment]
@perotom Thanks for reporting the issue. This does seem like a bug.

@artyLee Could you please take a look at this? Thanks.

**Comment by artyLee** [comment]
You're welcome! I try to look at this issue.
