### ISSUE TITLE
Argon not updating firmware OTA

### ISSUE THREAD

**Issue by Lotrax** [particle-iot/device-os#1990]
### Expected Behavior

Argon should be upgraded to new firmware and have the blink sketch uploaded.

### Observed Behavior

Firmware not updated (still on 1.3.1) and Argon is in a looping Safe Mode. I say looping Safe Mode, because it looks like it's in Safe Mode, but it then resets and tries to flash again (this gets posted to the Particle Console), however I cannot signal it or flash it again, however I can ping it and the console says it's connected. I need to manually set it to Safe Mode in orde for me to flash blink with firmware 1.3.1, after which the Argon works fine again.

All versions of the 1.4.X firmware (including prereleases) give this result.

### Steps to Reproduce

0. Get a new Argon (bought this last week), not sure if it matters.

1. Have the Argon connected to the Particle Cloud and on firmware version 1.3.1.
2. Open web IDE and load the blink example.
3. Select the latest firmware.
4. Flash.
5. Observe.
6. Manually place the Argon in Safe Mode.
7. Upload the blink example with 1.3.1 firmware.
8. All works.

**Comment by No1089** [comment]
@Lotrax If you are still experiencing this issue, please create a ticket at support.particle.io so a support team memeber can assist.
