### ISSUE TITLE
BleAddress could do with a way to check validity and also invalidate an object

### ISSUE THREAD

**Issue by ScruffR** [particle-iot/device-os#2005]
While `BleUuid` features an `isValid()` and `BleCharacteristic` a `valid()` method I was surprised to find that `BleAddress` does *not*.
It would be good practice to have a *consistent* way to check validity *and also* a simple and consistent way to _invalidate_ and object (e.g. like `IPAddress::clear()`)

When I say *"consistent"*, I'm thinking of `BleUuid::isValid()` vs. `BleCharacteristic::valid()` - IMO that is *very poor* style and suggests there were two individuals working on the same project but not speaking with eachother (that reminds me of [this](https://github.com/particle-iot/device-os/issues/1711) blunder with the EtherWing design where obviously the context and preexisting devices were *not* considered in the planning process).
Or if it was only a single coder I'd have that looked at :wink:

**Comment by ScruffR** [comment]
Bump!

**Comment by avtolstoy** [comment]
Fixed in #2222
