### ISSUE TITLE
Now that mesh is dead, Local.publish() over local WiFi network anyone?

### ISSUE THREAD

**Issue by karlg100** [particle-iot/device-os#2013]
### References

https://community.particle.io/t/feature-request-new-primitive-local-publish-for-wifi-devices/45668/21

---

## Feature/Enhancement Request

Now that mesh is dead, and we’re all relying on Mesh.publish() to locally delivery publish/subscribe messages among our devices, any chance we can get local.publish() or some equivalent to locally use the network connection for similar functionality?  I need a way to exchange messages among devices.

I’m already going to have to rework to take mesh out of my code, would be great to have similar functionality over an existing network connection without having to route out to the cloud.

**Comment by sergeuz** [comment]
Thank you for reaching out. It should be possible to factor out the dependency on the mesh network interface in the [existing implementation](https://github.com/particle-iot/device-os/blob/1f92f7899f6b31b5d2851605e147a1d8560bece4/wiring/src/spark_wiring_mesh.cpp#L136-L172). We have no plans on implementing this feature though.
