### ISSUE TITLE
Photon not going to sleep mode

### ISSUE THREAD

**Issue by nitinjs** [particle-iot/device-os#2063]
<details>
  <summary><i>I wrote following sketch to sleep the photon after 70 seconds if wifi is not found
however it is not going to sleep mode</i></summary>
</details>

### Expected Behavior

Should go to sleep mode after 70 seconds

### Observed Behavior

Keeps on blinking green

### Steps to Reproduce

Flash the firmware and run without turning on wifi access point

### Test App

```c
SYSTEM_MODE(SEMI_AUTOMATIC);

int secAlive = 70;
bool isConnectTriggered = false;
bool isConnected = false;
int secPassedSinceTrigger = 0;
int secPrev = Time.local() % 86400;

void triggerConnect(){
    Particle.connect();
    isConnectTriggered = true;
    secPrev = Time.local() % 86400;
    secPassedSinceTrigger = 0;
}

void setup() {
    if(isConnectTriggered==false){
        triggerConnect();
    }
}

void loop() {
    if(isConnectTriggered==true){
        if(isConnected == false){
            int secNow = Time.local() % 86400;
            secPassedSinceTrigger = secNow - secPrev;
        }
        
        isConnected = Particle.connected();
            
        if(isConnected == false){
            if(secPassedSinceTrigger>= secAlive){
                int sec24Hours = 86400;
                System.sleep(SLEEP_MODE_DEEP, sec24Hours);
            }
        }else{
            //connected proceed to work
            Particle.publish("connected", String(isConnected));
            Particle.publish("Seconds Passed", String(secPassedSinceTrigger));
        }
    }
    delay(1000);
}
```

### References

https://community.particle.io/t/shutting-down-photon-after-1-minute-if-configured-wifi-not-found/55329

---

is this a bug or I am missing something?

**Comment by avtolstoy** [comment]
@nitinjs Thanks for reporting the issue.

You are in `SEMI_AUTOMATIC` mode. Your `setup()` function triggers the connection to cloud and wifi network, and the `loop()` function won't get executed until that succeeds. This is documented in https://docs.particle.io/reference/device-os/firmware/photon/#system-modes.
