### ISSUE TITLE
Cellular Data reported with "ERR" in DIAG Update FW 1.5.0

### ISSUE THREAD

**Issue by ahk97** [particle-iot/device-os#2066]
## Bug Report
After Electron Firmware update to 1.5.0 the Cellular Info reported in the Device Diag mostly contains "ERR".
The following data is not reported:
mobile_country_code
mobile_network_code
location_area_code
cell_id

Examples:
{"name":"spark/device/diagnostics/update","data":"{\"device\":{\"network\":{\"cellular\":{\"radio_access_technology\":\"3G\",\"cell_global_identity\":{\"mobile_country_code\":{\"err\":-1200},\"mobile_network_code\":{\"err\":-1200},\"location_area_code\":{\"err\":-1200},\"cell_id\":{\"err\":-1200}}},\"signal\":{\"at\":\"UMTS\",\"strength\":15.62,\"strength_units\":\"%\",\"strengthv\":-106,\"strengthv_units\":\"dBm\",\"strengthv_type\":\"RSCP\",\"quality\":75.51,\"quality_units\":\"%\",\"qualityv\":-6,\"qualityv_units\":\"dB\",\"qualityv_type\":\"ECN0\"},\"connection\":{\"status\":\"connected\",\"error\":0,\"disconnects\":2,\"attempts\":1,\"disconnect_reason\":\"network_off\"}},\"cloud\":{\"connection\":{\"status\":\"connected\",\"error\":0,\"attempts\":1,\"disconnects\":2,\"disconnect_reason\":\"network_disconnect\"},\"coap\":{\"unack\":0},\"publish\":{\"rate_limited\":0}},\"power\":{\"battery\":{\"charge\":{\"err\":-210},\"state\":\"disconnected\"},\"source\":\"VIN\"},\"system\":{\"uptime\":9231,\"memory\":{\"used\":58112,\"total\":113664}}},\"service\":{\"device\":{\"status\":\"ok\"},\"cloud\":{\"uptime\":110,\"publish\":{\"sent\":3}},\"coap\":{\"round_trip\":1711}}}","ttl":60,"published_at":"2020-04-01T09:41:43.442Z","coreid":"xxx"}

{"name":"spark/device/diagnostics/update","data":"{\"device\":{\"network\":{\"cellular\":{\"radio_access_technology\":\"2G\",\"cell_global_identity\":{\"mobile_country_code\":{\"err\":-1200},\"mobile_network_code\":{\"err\":-1200},\"location_area_code\":{\"err\":-1200},\"cell_id\":{\"err\":-1200}}},\"signal\":{\"at\":\"GSM\",\"strength\":79.36,\"strength_units\":\"%\",\"strengthv\":-61,\"strengthv_units\":\"dBm\",\"strengthv_type\":\"RXLEV\",\"quality\":{\"err\":-100},\"qualityv\":{\"err\":-100}},\"connection\":{\"status\":\"connected\",\"error\":0,\"disconnects\":0,\"attempts\":1,\"disconnect_reason\":\"none\"}},\"cloud\":{\"connection\":{\"status\":\"connecting\",\"error\":0,\"attempts\":1,\"disconnects\":0,\"disconnect_reason\":\"none\"},\"coap\":{\"unack\":0},\"publish\":{\"rate_limited\":0}},\"power\":{\"battery\":{\"charge\":0,\"state\":\"not_charging\"},\"source\":\"VIN\"},\"system\":{\"uptime\":8,\"memory\":{\"used\":54488,\"total\":113664}}},\"service\":{\"device\":{\"status\":\"ok\"},\"cloud\":{\"uptime\":4,\"publish\":{\"sent\":2}},\"coap\":{\"round_trip\":2308}}}","ttl":60,"published_at":"2020-04-01T09:38:12.830Z","coreid":"4xxxxx"}

### Expected Behavior

In FW 1.4.3 it looked like this:
{"name":"spark/device/diagnostics/update","data":"{\"device\":{\"network\":{\"cellular\":{\"radio_access_technology\":\"2G\",\"operator\":\"T-mobile/Telekom\",\"cell_global_identity\":{\"mobile_country_code\":262,\"mobile_network_code\":\"01\",\"location_area_code\":18716,\"cell_id\":9886}},\"signal\":{\"at\":\"GSM\",\"strength\":79.36,\"strength_units\":\"%\",\"strengthv\":-61,\"strengthv_units\":\"dBm\",\"strengthv_type\":\"RXLEV\",\"quality\":{\"err\":-100},\"qualityv\":{\"err\":-100}},\"connection\":{\"status\":\"connected\",\"error\":0,\"disconnects\":0,\"attempts\":1,\"disconnect_reason\":\"none\"}},\"cloud\":{\"connection\":{\"status\":\"connected\",\"error\":0,\"attempts\":1,\"disconnects\":0,\"disconnect_reason\":\"none\"},\"coap\":{\"unack\":0},\"publish\":{\"rate_limited\":0}},\"power\":{\"battery\":{\"charge\":0,\"state\":\"not_charging\"},\"source\":\"VIN\"},\"system\":{\"uptime\":111682,\"memory\":{\"used\":57936,\"total\":113664}}},\"service\":{\"device\":{\"status\":\"ok\"},\"cloud\":{\"uptime\":137783,\"publish\":{\"sent\":1154}},\"coap\":{\"round_trip\":1600}}}","ttl":60,"published_at":"2020-04-01T09:51:35.805Z","coreid":"xxxx"}

### Steps to Reproduce

Upgrade Electron Firmware to 1.5.0

**Comment by avtolstoy** [comment]
Thanks for the report. Confirmed that the issue is present on Electron, however other cellular platforms are also affected since https://github.com/particle-iot/device-os/commit/8beeb0e358c23b52244aece68791307a5e440d8e (1.3.0-rc.1) and CGI worked/works on other them only by chance.
