### ISSUE TITLE
System.powersource() not updating at start

### ISSUE THREAD

**Issue by AndrewMoscoe** [particle-iot/device-os#2241]
<details>
  <summary><i>System.powersource() works fine if you call it in loop(), but returns 0 if I call it in setup()</i></summary>
</details>

### Expected Behavior

System.powersource() should return the proper power source both in setup() and loop()

### Observed Behavior

System.powersource() returns 0 in setup, and works in loop()

### Steps to Reproduce

See below app. I'm running this on a  Boron LTE, DeviceOS 2.0.0-RC4

The LED flashes indicate the power source as detected in the loop properly, but fail for the power source at the start. This happens both when plugged into USB and on battery power.

### Test App

```c
SYSTEM_MODE(SEMI_AUTOMATIC)

int powerAtStart;
void setup() {
  pinMode(D7, OUTPUT);
  powerAtStart = System.powerSource();

}

void loop() {
  ledFlash(powerAtStart + 1);
  delay(1000);
  ledFlash(System.powerSource() + 1);
  delay(1000);
}

void ledFlash(int num) {
  for(; num > 0; num--) {
    digitalWrite(D7, HIGH);
    delay(250);
    digitalWrite(D7, LOW);
    delay(250);
  }
}
```

**Comment by avtolstoy** [comment]
Thanks for the issue report.

This is the intended behavior, especially considering `SEMI_AUTOMATIC`, `MANUAL` or threaded modes where `setup()` runs as soon as possible. The PMIC and power management subsystem require some time to figure out the type of the power source (up to 500ms in some cases), before it can be reported to the application. Waiting for it to become valid before running `setup()` negates all the benefits of the aforementioned modes.

The same condition (`POWER_SOURCE_UNKNOWN`) may also very well happen during runtime if for example power supply is unplugged/re-plugged.
