### ISSUE TITLE
[core] support for wakeup pin

### ISSUE THREAD

**Issue by m-mcgowan** [particle-iot/device-os#640]
The wakepup pin support was never released, and was removed here since it caused A0 to not function as expected.  https://github.com/spark/firmware/issues/595

Wakeup on the core is a useful feature, so let's investigate what it takes to get this working!

**Comment by schwiet** [comment]
are these bugs related (#655)? did wakeup on the core ever get supported? It seems to work intermittently for me, but not reliable. Thanks.

**Comment by m-mcgowan** [comment]
I don't believe they are related. The WKP pin on the Core functions differently to how the EXTI interrupts are handled with stop mode.  Please see issue #595 for why we dropped the attempted and unreleased implementation of WKP on the Core. 

If you, or anyone else, is able to investigate why the wakeup code caused A0 to malfunction that would be very much welcomed!

**Comment by schwiet** [comment]
Ok, thanks for the reply. So just to be sure I understand, `System.sleep( pin, mode )` is not supported on the Core? The documentation does imply that this should function properly using an updated boot loader.

**Comment by m-mcgowan** [comment]
`System.sleep(SLEEP_MODE_DEEP, time)` isn't supported since the wakeup pin (A0) isn't configured as wakeup on the Core. 

`System.sleep(pin,mode,duration)` works, where duration can be 0 for no timed wakeup.
