### ISSUE TITLE
Particle.function returning double (C++ class member)

### ISSUE THREAD

**Issue by elevatorguy** [particle-iot/device-os#981]
In 0.5.0 on electron.
Not a big deal, as we can attach a global function returning a double to Particle.function

returning int works in classes, but returning double in classes would be nice:

```c
// EXAMPLE USAGE WITH C++ OBJECT
class CoffeeMaker {
   public:
    CoffeeMaker() {
      Particle.function("brew", &CoffeeMaker::brew, this);
    }

    double brew(String command) {
      // do stuff
      return 1;
    }
};

CoffeeMaker myCoffeeMaker;
// nothing else needed in setup() or loop()
```

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (0.5.0)

**Comment by m-mcgowan** [comment]
To make this work requires more than just a syntactic change in firmware - the function registration in the cloud would need to be changed too so that the `double` is properly treated as a floating point number rather than as a 32-bit integer.

**Comment by technobly** [comment]
This compiles, but currently returns a truncated result due to conversion to 32-bit integer as Mat mentioned.  I'm not sure why we allow this to compile though without error if it doesn't do what it looks like it should do.

```c
double brewGlobal(String command) {
    // do stuff
    return 3.14159;
}

void setup() {
    Particle.function("brew-global", brewGlobal);
}
```
